#!/usr/bin/env bash
set -eo pipefail

host=`hostname`
if [[ ! -z "$1" ]]; then
  host=$1
fi

if [[ ! -e "hosts/$host.nix" ]] || [[ ! -e "hosts/$host-hardware.nix" ]]; then
  echo "missing $host.nix or $host-hardware.nix" >&2
  exit 1
fi

ln -f -v "hosts/$host.nix" configuration.nix
ln -f -v "hosts/$host-hardware.nix" hardware-configuration.nix
